const images = {
  backGround: require("./imageBG/BG.png"),
  iconHome: require("./iconBottom/home.png"),
  iconVoucher: require("./iconBottom/voucher.png"),
  iconWallet: require("./iconBottom/wallet.png"),
  iconUser: require("./iconBottom/account.png"),
  banner: require("./banner/banner.png"),
  icon1: require("./category/ico1.png"),
  icon2: require("./category/ico2.png"),
  icon3: require("./category/ico3.png"),
  icon4: require("./category/ico4.png"),
  layer1: require("./banner/Layer1.png"),
  pro1: require("./product/iphone.png"),
  pro2: require("./product/xbox.png"),
  pro3: require("./product/xbox.png"),
  logo_urbox: require("./Logos_Brand/logoUrboxFinal1.png"),
  logo_the_coffee_house: require("./Logos_Brand/icon.png"),
  logo_mobifone: require("./Logos_Brand/mobifone.png"),
  logo_vinid: require("./Logos_Brand/vinId.png"),
  logo_bee: require("./Logos_Brand/appLogoBe.png"),
  logo_dienmayxanh: require("./Logos_Brand/appLogoDienMayXanh.png"),
  icon_search: require("./icon-Cross/ico_Search.png"),
  cross: require("./icon-Cross/bt.png"),
  witness: require("./icon-Cross/witness.png"),
  plus: require("./icon-Cross/plus.png"),
  chat: require("./icon-Cross/Chat.png"),
  detail: require("./imageBG/Voucher_default.png"),
  times: require("./icon-Cross/ico_calendar.png"),
  frame_item: require("./product/Frame_Item.png")
};
export default images;
